<?php

use Illuminate\Database\Seeder;

class DiagnosticsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		$codes = array (
			'B22.0','F00','F00.0','F00.1','F00.2','F00.9','F01','F01.0','F01.1','F01.2','F01.3','F01.8','F01.9','F02','F02.0','F02.1','F02.2','F02.3','F02.4','F02.8','F03','F04','F05','F05.0','F05.1','F05.8','F05.9','F06','F06.0','F06.1','F06.2','F06.3','F06.4','F06.5','F06.6','F06.7','F06.8','F06.9','F07','F07.0','F07.1','F07.2','F07.8','F07.9','F09','F10','F10.0','F10.1','F10.2','F10.3','F10.4','F10.5','F10.6','F10.7','F10.8','F10.9','F11','F11.0','F11.1','F11.2','F11.3','F11.4','F11.5','F11.6','F11.7','F11.8','F11.9','F12','F12.0','F12.1','F12.2','F12.3','F12.4','F12.5','F12.6','F12.7','F12.8','F12.9','F13','F13.0','F13.1','F13.2','F13.3','F13.4','F13.5','F13.6','F13.7','F13.8','F13.9','F14','F14.0','F14.1','F14.2','F14.3','F14.4','F14.5','F14.6','F14.7','F14.8','F14.9','F15','F15.0','F15.1','F15.2','F15.3','F15.4','F15.5','F15.6','F15.7','F15.8','F15.9','F16','F16.0','F16.1','F16.2','F16.3','F16.4','F16.5','F16.6','F16.7','F16.8','F16.9','F17','F17.0','F17.1','F17.2','F17.3','F17.4','F17.5','F17.6','F17.7','F17.8','F17.9','F18','F18.0','F18.1','F18.2','F18.3','F18.4','F18.5','F18.6','F18.7','F18.8','F18.9','F19','F19.0','F19.1','F19.2','F19.3','F19.4','F19.5','F19.6','F19.7','F19.8','F19.9','F20','F20.0','F20.1','F20.2','F20.3','F20.4','F20.5','F20.6','F20.8','F20.9','F21','F22','F22.0','F22.8','F22.9','F23','F23.0','F23.1','F23.2','F23.3','F23.8','F23.9','F24','F25','F25.0','F25.1','F25.2','F25.8','F25.9','F28','F29','F30','F30.0','F30.1','F30.2','F30.8','F30.9','F31','F31.0','F31.1','F31.2','F31.3','F31.4','F31.5','F31.6','F31.7','F31.8','F31.9','F32','F32.0','F32.1','F32.2','F32.3','F32.8','F32.9','F33','F33.0','F33.1','F33.2','F33.3','F33.4','F33.8','F33.9','F34','F34.0','F34.1','F34.8','F34.9','F38','F38.0','F38.1','F38.8','F39','F40','F40.0','F40.1','F40.2','F40.8','F40.9','F41','F41.0','F41.1','F41.2','F41.3','F41.8','F41.9','F42','F42.0','F42.1','F42.2','F42.8','F42.9','F43','F43.0','F43.1','F43.2','F43.8','F43.9','F44','F44.0','F44.1','F44.2','F44.3','F44.4','F44.5','F44.6','F44.7','F44.8','F44.9','F45','F45.0','F45.1','F45.2','F45.3','F45.4','F45.8','F45.9','F48','F48.0','F48.1','F48.8','F48.9','F50','F50.0','F50.1','F50.2','F50.3','F50.4','F50.5','F50.8','F50.9','F51','F51.0','F51.1','F51.2','F51.3','F51.4','F51.5','F51.8','F51.9','F52','F52.0','F52.1','F52.2','F52.3','F52.4','F52.5','F52.6','F52.7','F52.8','F52.9','F53','F53.0','F53.1','F53.8','F53.9','F54','F55','F59','F60','F60.0','F60.1','F60.2','F60.3','F60.4','F60.5','F60.6','F60.7','F60.8','F60.9','F61','F62','F62.0','F62.1','F62.8','F62.9','F63','F63.0','F63.1','F63.2','F63.3','F63.8','F63.9','F64','F64.0','F64.1','F64.2','F64.8','F64.9','F65','F65.0','F65.1','F65.2','F65.3','F65.4','F65.5','F65.6','F65.8','F65.9','F66','F66.0','F66.1','F66.2','F66.8','F66.9','F68','F68.0','F68.1','F68.8','F69','F70','F70.0','F70.1','F70.8','F70.9','F71','F71.0','F71.1','F71.8','F71.9','F72','F72.0','F72.1','F72.8','F72.9','F73','F73.0','F73.1','F73.8','F73.9','F78','F78.0','F78.1','F78.8','F78.9','F79','F79.0','F79.1','F79.8','F79.9','F80','F80.0','F80.1','F80.2','F80.3','F80.8','F80.9','F81','F81.0','F81.1','F81.2','F81.3','F81.8','F81.9','F82','F83','F84','F84.0','F84.1','F84.2','F84.3','F84.4','F84.5','F84.8','F84.9','F88','F89','F90','F90.0','F90.1','F90.8','F90.9','F91','F91.0','F91.1','F91.2','F91.3','F91.8','F91.9','F92','F92.0','F92.8','F92.9','F93','F93.0','F93.1','F93.2','F93.3','F93.8','F93.9','F94','F94.0','F94.1','F94.2','F94.8','F94.9','F95','F95.0','F95.1','F95.2','F95.8','F95.9','F98','F98.0','F98.1','F98.2','F98.3','F98.4','F98.5','F98.6','F98.8','F98.9','F99','G10','G20','G21.0','G21.1','G21.1','G24.0','G24.0','G25.1','G25.9','G30','G31.0','G47.0','G47.1','G47.3','G47.4','G47.8','K59.0','N48.4','N50.8','N94.1','N94.8','R15','R41.3','R41.8','R46.8','R69','S06.9','T74.0','T74.1','T74.2','T88.7','Z03.2','Z55.8','Z56.7','Z60.0','Z60.3','Z63.0','Z63.1','Z63.4','Z63.7','Z63.8','Z63.9','Z71.8','Z72.8','Z91.1'
			);

		$descriptions = array (
			'Enfermedad por VIH, resultante en encefalopat¡a',
			'Demencia en la enfermedad de Alzheimer (G30.-+)',
			'Demencia en la enfermedad de Alzheimer, de comienzo temprano (G30.0+)',
			'Demencia en la enfermedad de Alzheimer, de comienzo tard¡o (G30.1+)',
			'Demencia en la enfermedad de Alzheimer, at¡pica o de tipo mixto (G30.8+)',
			'Demencia en la enfermedad de Alzheimer, no especificada (G30.9+)',
			'Demencia vascular',
			'Demencia vascular de comienzo agudo',
			'Demencia vascular por infartos m£ltiples',
			'Demencia vascular subcortical',
			'Demencia vascular mixta, cortical y subcortical',
			'Otras demencias vasculares',
			'Demencia vascular, no especificada',
			'Demencia en otras enfermedades clasificadas en otra parte',
			'Demencia en la enfermedad de Pick (G3l.0+)',
			'Demencia en la enfermedad de Creutzfeldt-Jakob (A81.0+)',
			'Demencia en la enfermedad de Huntington (Gl0+)',
			'Demencia en la enfermedad de Parkinson (G20+)',
			'Demencia en la enfermedad por virus de la inmunodeficiencia humana [VIH] (B22.0+)',
			'Demencia en otras enfermedades especificadas clasificadas en otra parte',
			'Demencia, no especificada',
			'S¡ndrome amnésico organico, no inducido por alcohol o por otras sustancias psicoactivas',
			'Delirio, no inducido por alcohol o por otras sustancias psicoactivas',
			'Delirio no superpuesto a un cuadro de demencia, as¡ descrito',
			'Delirio superpuesto a un cuadro de demencia',
			'Otros delirios',
			'Delirio, no especificado',
			'Otros trastornos mentales debidos a lesión y disfunci¢n cerebral, y a enfermedad f¡sica',
			'Alucinosis organica',
			'Trastorno catat¢nico, organico',
			'Trastorno delirante [esquizofreniforme], organico',
			'Trastornos del humor [afectivos], organicos',
			'Trastorno de ansiedad, organico',
			'Trastorno disociativo, organico',
			'Trastorno de labilidad emocional [asténico], organico',
			'Trastorno cognoscitivo leve',
			'Otros trastornos mentales especificados debidos a lesi¢n y disfunci¢n cerebral y a enferme',
			'Trastorno mental no especificado debido a lesi¢n y disfunci¢n cerebral y a enfermedad f¡si',
			'Trastornos de la personalidad y del comportamiento debidos a enfermedad, lesi¢n o disfunci',
			'Trastorno de la personalidad, organico',
			'S¡ndrome postencefal¡tico',
			'S¡ndrome postconcusional',
			'Otros trastornos organicos de la personalidad y del comportamiento debidos a enfermedad, l',
			'Trastorno organico de la personalidad y del comportamiento, no especificado, debido a enfe',
			'Trastorno mental organico o sintom tico, no especificado',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, intoxicaci¢n aguda',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, uso nocivo',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, s¡ndrome de dependenci',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, estado de abstinencia',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, estado de abstinencia ',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, trastorno psic¢tico',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, s¡ndrome amnésico',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, trastorno psic¢tico re',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, otros trastornos menta',
			'Trastornos mentales y del comportamiento debidos al uso de alcohol, trastorno mental y del',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, intoxicaci¢n aguda',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, uso nocivo',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, s¡ndrome de dependenc',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, estado de abstinencia',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, estado de abstinencia',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, trastorno psic¢tico',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, s¡ndrome amnésico',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, trastorno psic¢tico r',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, otros trastornos ment',
			'Trastornos mentales y del comportamiento debidos al uso de opiaceos, trastorno mental y de',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, intoxicaci¢n agu',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, uso nocivo',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, s¡ndrome de depe',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, estado de abstin',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, estado de abstin',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, trastorno psic¢t',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, s¡ndrome amnésic',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, trastorno psic¢t',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, otros trastornos',
			'Trastornos mentales y del comportamiento debidos al uso de cannabinoides, trastorno mental',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, intoxica',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, uso noci',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, s¡ndrome',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, estado d',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, estado d',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, trastorn',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, s¡ndrome',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, trastorn',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, otros tr',
			'Trastornos mentales y del comportamiento debidos al uso de sedantes o hipn¢ticos, trastorn',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, intoxicaci¢n aguda',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, uso nocivo',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, s¡ndrome de dependenci',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, estado de abstinencia',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, estado de abstinencia ',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, trastorno psic¢tico',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, s¡ndrome amnésico',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, trastorno psic¢tico re',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, otros trastornos menta',
			'Trastornos mentales y del comportamiento debidos al uso de coca¡na, trastorno mental y del',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de otros estimulantes, incluida la',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, intoxicaci¢n agud',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, uso nocivo',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, s¡ndrome de depen',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, estado de abstine',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, estado de abstine',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, trastorno psic¢ti',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, s¡ndrome amnésico',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, trastorno psic¢ti',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, otros trastornos ',
			'Trastornos mentales y del comportamiento debidos al uso de alucin¢genos, trastorno mental ',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, intoxicaci¢n aguda',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, uso nocivo',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, s¡ndrome de dependencia',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, estado de abstinencia',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, estado de abstinencia c',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, trastorno psic¢tico',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, s¡ndrome amnésico',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, trastorno psic¢tico res',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, otros trastornos mental',
			'Trastornos mentales y del comportamiento debidos al uso de tabaco, trastorno mental y del ',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, intoxica',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, uso noci',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, s¡ndrome',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, estado d',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, estado d',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, trastorn',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, s¡ndrome',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, trastorn',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, otros tr',
			'Trastornos mentales y del comportamiento debidos al uso de disolventes volatiles, trastorn',
			'Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de m£ltiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de mútiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de mútiples drogas y al uso de ot',
			'Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de ot',
			'Esquizofrenia',
			'Esquizofrenia paranoide',
			'Esquizofrenia hebefrónica',
			'Esquizofrenia catat¢nica',
			'Esquizofrenia indiferenciada',
			'Depresi¢n postesquizofrénica',
			'Esquizofrenia residual',
			'Esquizofrenia simple',
			'Otras esquizofrenias',
			'Esquizofrenia, no especificada',
			'Trastorno esquizot¡pico',
			'Trastornos delirantes persistentes',
			'Trastorno delirante',
			'Otros trastornos delirantes persistentes',
			'Trastorno delirante persistente, no especificado',
			'Trastornos psic¢ticos agudos y transitorios',
			'Trastorno psic¢tico agudo polimorfo, sin s¡ntomas de esquizofrenia',
			'Trastorno psic¢tico agudo polimorfo, con s¡ntomas de esquizofrenia',
			'Trastorno psic¢tico agudo de tipo esquizofrénico',
			'Otro trastorno psic¢tico agudo, con predominio de ideas delirantes',
			'Otros trastornos psic¢ticos agudos y transitorios',
			'Trastorno psic¢tico agudo y transitorio, no especificado',
			'Trastorno delirante inducido',
			'Trastornos esquizoafectivos',
			'Trastorno esquizoafectivo de tipo man¡aco',
			'Trastorno esquizoafectivo de tipo depresivo',
			'Trastorno esquizoafectivo de tipo mixto',
			'Otros trastornos esquizoafectivos',
			'Trastorno esquizoafectivo, no especificado',
			'Otros trastornos psic¢ticos de origen no org nico',
			'Psicosis de origen no org nico, no especificada',
			'Episodio man¡aco',
			'Hipoman¡a',
			'Man¡a sin s¡ntomas psic¢ticos',
			'Man¡a con s¡ntomas psic¢ticos',
			'Otros episodios man¡acos',
			'Episodio man¡aco, no especificado',
			'Trastorno afectivo bipolar',
			'Trastorno afectivo bipolar, episodio hipoman¡aco presente',
			'Trastorno afectivo bipolar, episodio man¡aco presente sin s¡ntomas psic¢ticos',
			'Trastorno afectivo bipolar, episodio man¡aco presente con s¡ntomas psic¢ticos',
			'Trastorno afectivo bipolar, episodio depresivo presente leve o moderado',
			'Trastorno afectivo bipolar, episodio depresivo grave presente sin s¡ntomas psic¢ticos',
			'Trastorno afectivo bipolar, episodio depresivo grave presente con s¡ntomas psic¢ticos',
			'Trastorno afectivo bipolar, episodio mixto presente',
			'Trastorno afectivo bipolar, actualmente en remisi¢n',
			'Otros trastornos afectivos bipolares',
			'Trastorno afectivo bipolar, no especificado',
			'Episodio depresivo',
			'Episodio depresivo leve',
			'Episodio depresivo moderado',
			'Episodio depresivo grave sin s¡ntomas psic¢ticos',
			'Episodio depresivo grave con s¡ntomas psic¢ticos',
			'Otros episodios depresivos',
			'Episodio depresivo, no especificado',
			'Trastorno depresivo recurrente',
			'Trastorno depresivo recurrente, episodio leve presente',
			'Trastorno depresivo recurrente, episodio moderado presente',
			'Trastorno depresivo recurrente, episodio depresivo grave presente sin s¡ntomas psic¢ticos',
			'Trastorno depresivo recurrente, episodio depresivo grave presente, con s¡ntomas psic¢ticos',
			'Trastorno depresivo recurrente actualmente en remisi¢n',
			'Otros trastornos depresivos recurrentes',
			'Trastorno depresivo recurrente, no especificado',
			'Trastornos del humor [afectivos] persistentes',
			'Ciclotimia',
			'Distimia',
			'Otros trastornos del humor [afectivos] persistentes',
			'Trastorno persistente del humor [afectivo], no especificado',
			'Otros trastornos del humor [afectivos]',
			'Otros trastornos del humor [afectivos], aislados',
			'Otros trastornos del humor [afectivos], recurrentes',
			'Otros trastornos del humor [afectivos], especificados',
			'Trastorno del humor [afectivo], no especificado',
			'Trastornos f¢bicos de ansiedad',
			'Agorafobia',
			'Fobias sociales',
			'Fobias espec¡ficas (aisladas)',
			'Otros trastornos f¢bicos de ansiedad',
			'Trastorno f¢bico de ansiedad, no especificado',
			'Otros trastornos de ansiedad',
			'Trastorno de p nico [ansiedad parox¡stica epis¢dica]',
			'Trastorno de ansiedad generalizada',
			'Trastorno mixto de ansiedad y depresi¢n',
			'Otros trastornos de ansiedad mixtos',
			'Otros trastornos de ansiedad especificados',
			'Trastorno de ansiedad, no especificado',
			'Trastorno obsesivo-compulsivo',
			'Predominio de pensamientos o rumiaciones obsesivas',
			'Predominio de actos compulsivos [rituales obsesivos]',
			'Actos e ideas obsesivas mixtos',
			'Otros trastornos obsesivo-compulsivos',
			'Trastorno obsesivo-compulsivo, no especificado',
			'Reacci¢n al estrés grave y trastornos de adaptaci¢n',
			'Reacci¢n al estrés agudo',
			'Trastorno de estrés postraum tico',
			'Trastornos de adaptaci¢n',
			'Otras reacciones al estrés grave',
			'Reacci¢n al estrés grave, no especificada',
			'Trastornos disociativos [de conversi¢n]',
			'Amnesia disociativa',
			'Fuga disociativa',
			'Estupor disociativo',
			'Trastornos de trance y de posesi¢n',
			'Trastornos disociativos del movimiento',
			'Convulsiones disociativas',
			'Anestesia disociativa y pérdida sensorial',
			'Trastornos disociativos mixtos [y de conversi¢n]',
			'Otros trastornos disociativos [de conversi¢n]',
			'Trastorno disociativo [de conversión], no especificado',
			'Trastornos somatomorfos',
			'Trastorno de somatizaci¢n',
			'Trastorno somatomorfo indiferenciado',
			'Trastorno hipocondr¡aco',
			'Disfunci¢n auton¢mica somatomorfa',
			'Trastorno de dolor persistente somatomorfo',
			'Otros trastornos somatomorfos',
			'Trastorno somatomorfo, no especificado',
			'Otros trastornos neur¢ticos',
			'Neurastenia',
			'S¡ndrome de despersonalizaci¢n y desvinculaci¢n de la realidad',
			'Otros trastornos neur¢ticos especificados',
			'Trastorno neur¢tico, no especificado',
			'Trastornos de la ingesti¢n de alimentos',
			'Anorexia nerviosa',
			'Anorexia nerviosa at¡pica',
			'Bulimia nerviosa',
			'Bulimia nerviosa at¡pica',
			'Hiperfagia asociada con otras alteraciones psicol¢gicas',
			'V¢mitos asociados con otras alteraciones psicol¢gicas',
			'Otros trastornos de la ingesti¢n de alimentos',
			'Trastorno de la ingesti¢n de alimentos, no especificado',
			'Trastornos no org nicos del suelo',
			'Insomnio no organico',
			'Hipersomnio no organico',
			'Trastorno no organico del ciclo sue¤o-vigilia',
			'Sonambulismo',
			'Terrores del sue¤o [terrores nocturnos]',
			'Pesadillas',
			'Otros trastornos no org nicos del sueÏo',
			'Trastorno no organico del sue¤o, no especificado',
			'Disfunci¢n sexual no ocasionada por trastorno ni enfermedad organicos',
			'Falta o pérdida del deseo sexual',
			'Aversi¢n al sexo y falta de goce sexual',
			'Falla de la respuesta genital',
			'Disfunci¢n orgasmica',
			'Eyaculaci¢n precoz',
			'Vaginismo no organico',
			'Dispareunia no organica',
			'Impulso sexual excesivo',
			'Otras disfunciones sexuales, no ocasionadas por trastorno ni por enfermedad org nicos',
			'Disfunci¢n sexual no ocasionada por trastorno ni por enfermedad organicos, no especificada',
			'Trastornos mentales y del comportamiento asociados con el puerperio, no clasificados en ot',
			'Trastornos mentales y del comportamiento leves, asociados con el puerperio, no clasificado',
			'Trastornos mentales y del comportamiento graves, asociados con el puerperio, no clasificad',
			'Otros trastornos mentales y del comportamiento asociados con el puerperio, no clasificados',
			'Trastorno mental puerperal, no especificado',
			'Factores psicol¢gicos y del comportamiento asociados con trastornos o enfermedades clasifi',
			'Abuso de sustancias que no producen dependencia',
			'S¡ndromes del comportamiento asociados con alteraciones fisiol¢gicas y factores f¡sicos, n',
			'Trastornos espec¡ficos de la personalidad',
			'Trastorno paranoide de la personalidad',
			'Trastorno esquizoide de la personalidad',
			'Trastorno asocial de la personalidad',
			'Trastorno de la personalidad emocionalmente inestable',
			'Trastorno histri¢nico de la personalidad',
			'Trastorno ananc stico de la personalidad',
			'Trastorno de la personalidad ansiosa (evasiva, elusiva)',
			'Trastorno de la personalidad dependiente',
			'Otros trastornos espec¡ficos de la personalidad',
			'Trastorno de la personalidad, no especificado',
			'Trastornos mixtos y otros trastornos de la personalidad',
			'Cambios perdurables de la personalidad, no atribuibles a lesi¢n o a enfermedad cerebral',
			'Cambio perdurable de la personalidad después de una experiencia catastr¢fica',
			'Cambio perdurable de la personalidad consecutivo a una enfermedad psiquiatrica',
			'Otros cambios perdurables de la personalidad',
			'Cambio perdurable de la personalidad, no especificado',
			'Trastornos de los habitos y de los impulsos',
			'Juego patol¢gico',
			'Piroman¡a',
			'Hurto patol¢gico [cleptoman¡a]',
			'Tricotiloman¡a',
			'Otros trastornos de los h bitos y de los impulsos',
			'Trastorno de los h bitos y de los impulsos, no especificado',
			'Trastornos de la identidad de género',
			'Transexualismo',
			'Transvestismo de rol dual',
			'Trastorno de la identidad de género en la ni¤ez',
			'Otros trastornos de la identidad de género',
			'Trastorno de la identidad de género, no especificado',
			'Trastornos de la preferencia sexual',
			'Fetichismo',
			'Transvestismo fetichista',
			'Exhibicionismo',
			'Voyeurismo',
			'Pedofilia',
			'Sadomasoquismo',
			'Trastornos m£ltiples de la preferencia sexual',
			'Otros trastornos de la preferencia sexual',
			'Trastorno de la preferencia sexual, no especificado',
			'Trastornos psicol¢gicos y del comportamiento asociados con el desarrollo y con la orientac',
			'Trastorno de la maduraci¢n sexual',
			'Orientaci¢n sexual egodist¢nica',
			'Trastorno de la relaci¢n sexual',
			'Otros trastornos del desarrollo psicosexual',
			'Trastorno del desarrollo psicosexual, no especificado',
			'Otros trastornos de la personalidad y del comportamiento en adultos',
			'Elaboraci¢n de s¡ntomas f¡sicos por causas psicol¢gicas',
			'Producci¢n intencional o simulaci¢n de s¡ntomas o de incapacidades, tanto f¡sicas como psi',
			'Otros trastornos especificados de la personalidad y del comportamiento en adultos',
			'Trastorno de la personalidad y del comportamiento en adultos, no especificado',
			'Retraso mental leve',
			'Retraso mental leve, deterioro del comportamiento nulo o m¡nimo',
			'Retraso mental leve, deterioro del comportamiento significativo, que requiere atenci¢n o t',
			'Retraso mental leve, otros deterioros del comportamiento',
			'Retraso mental leve, deterioro del comportamiento de grado no especificado',
			'Retraso mental moderado',
			'Retraso mental moderado, deterioro del comportamiento nulo o m¡nimo',
			'Retraso mental moderado, deterioro del comportamiento significativo, que requiere atenci¢n',
			'Retraso mental moderado, otros deterioros del comportamiento',
			'Retraso mental moderado, deterioro del comportamiento de grado no especificado',
			'Retraso mental grave',
			'Retraso mental grave, deterioro del comportamiento nulo o m¡nimo',
			'Retraso mental grave, deterioro del comportamiento significativo, que requiere atenci¢n o ',
			'Retraso mental grave, otros deterioros del comportamiento',
			'Retraso mental grave, deterioro del comportamiento de grado no especificado',
			'Retraso mental profundo',
			'Retraso mental profundo, deterioro del comportamiento nulo o m¡nimo',
			'Retraso mental profundo, deterioro del comportamiento significativo, que requiere atenci¢n',
			'Retraso mental profundo, otros deterioros del comportamiento',
			'Retraso mental profundo, deterioro del comportamiento de grado no especificado',
			'Otros tipos de retraso mental',
			'Otros tipos de retraso mental, deterioro del comportamiento nulo o m¡nimo',
			'Otros tipos de retraso mental, deterioro del comportamiento significativo, que requiere at',
			'Otros tipos de retraso mental, otros deterioros del comportamiento',
			'Otros tipos de retraso mental, deterioro del comportamiento de grado no especificado',
			'Retraso mental, no especificado',
			'Retraso mental, no especificado, deterioro del comportamiento nulo o m¡nimo',
			'Retraso mental, no especificado, deterioro del comportamiento significativo, que requiere ',
			'Retraso mental, no especificado, otros deterioros del comportamiento',
			'Retraso mental, no especificado, deterioro del comportamiento de grado no especificado',
			'Trastornos espec¡ficos del desarrollo del habla y del lenguaje',
			'Trastorno espec¡fico de la pronunciaci¢n',
			'Trastorno del lenguaje expresivo',
			'Trastorno de la recepci¢n del lenguaje',
			'Afasia adquirida con epilepsia [Landau-Kleffner]',
			'Otros trastornos del desarrollo del habla y del lenguaje',
			'Trastorno del desarrollo del habla y del lenguaje no especificado',
			'Trastornos espec¡ficos del desarrollo de las habilidades escolares',
			'Trastorno espec¡fico de la lectura',
			'Trastorno espec¡fico del deletreo [ortograf¡a]',
			'Trastorno espec¡fico de las habilidades aritméticas',
			'Trastorno mixto de las habilidades escolares',
			'Otros trastornos del desarrollo de las habilidades escolares',
			'Trastorno del desarrollo de las habilidades escolares, no especificado',
			'Trastorno espec¡fico del desarrollo de la funci¢n motriz',
			'Trastornos espec¡ficos mixtos del desarrollo',
			'Trastornos generalizados del desarrollo',
			'Autismo en la ni¤ez',
			'Autismo at¡pico',
			'S¡ndrome de Rett',
			'Otro trastorno desintegrativo de la ni¤ez',
			'Trastorno hiperactivo asociado con retraso mental y movimientos estereotipados',
			'S¡ndrome de Asperger',
			'Otros trastornos generalizados del desarrollo',
			'Trastorno generalizado del desarrollo no especificado',
			'Otros trastornos del desarrollo psicol¢gico',
			'Trastorno del desarrollo psicol¢gico, no especificado',
			'Trastornos hipercinéticos',
			'Perturbaci¢n de la actividad y de la atenci¢n',
			'Trastorno hipercinético de la conducta',
			'Otros trastornos hipercinéticos',
			'Trastorno hipercinético, no especificado',
			'Trastornos de la conducta',
			'Trastorno de la conducta limitado al contexto familiar',
			'Trastorno de la conducta insociable',
			'Trastorno de la conducta sociable',
			'Trastorno opositor desafiante',
			'Otros trastornos de la conducta',
			'Trastorno de la conducta, no especificado',
			'Trastornos mixtos de la conducta y de las emociones',
			'Trastorno depresivo de la conducta',
			'Otros trastornos mixtos de la conducta y de las emociones',
			'Trastorno mixto de la conducta y de las emociones, no especificado',
			'Trastornos emocionales de comienzo espec¡fico en la niÏez',
			'Trastorno de ansiedad de separaci¢n en la niÏez',
			'Trastorno de ansiedad f¢bica en la ni¤ez',
			'Trastorno de ansiedad social en la ni¤ez',
			'Trastorno de rivalidad entre hermanos',
			'Otros trastornos emocionales en la ni¤ez',
			'Trastorno emocional en la niñez, no especificado',
			'Trastornos del comportamiento social de comienzo espec¡fico en la ni¤ez y en la adolescenc',
			'Mutismo electivo',
			'Trastorno de vinculaci¢n reactiva en la ni¤ez',
			'Trastorno de vinculaci¢n desinhibida en la ni¤ez',
			'Otros trastornos del comportamiento social en la ni¤ez',
			'Trastorno del comportamiento social en la ni¤ez, no especificado',
			'Trastornos por tics',
			'Trastorno por tic transitorio',
			'Trastorno por tic motor o vocal cr¢nico',
			'Trastorno por tics motores y vocales m£ltiples combinados [de la Tourette]',
			'Otros trastornos por tics',
			'Trastorno por tic, no especificado',
			'Otros trastornos emocionales y del comportamiento que aparecen habitualmente en la ni¤ez y',
			'Enuresis no organica',
			'Encopresis no organica',
			'Trastorno de la ingesti¢n alimentaria en la infancia y la ni¤ez',
			'Pica en la infancia y la ni¤ez',
			'Trastornos de los movimientos estereotipados',
			'Tartamudez [espasmofemia]',
			'Farfulleo',
			'Otros trastornos emocionales y del comportamiento que aparecen habitualmente en la ni¤ez y',
			'Trastornos no especificados, emocionales y del comportamiento, que aparecen habitualmente ',
			'Trastorno mental, no especificado',
			'Demencia debida a Enfermedad de Huntington',
			'Demencia debida a Enfermedad de Parkinson',
			'S¡ndrome neuroléptico maligno',
			'Acaticia inducida por neurolepticos',
			'Otro parkinsonismo secundario inducido por drogas',
			'Diston¡a inducida por drogas',
			'Discinencia tardía inducida por neurolepticos',
			'Temblor postural inducido por drogas',
			'Trastorno motor inducido por medicamentos no especificado',
			'Demencia tipo de Alzheimer (en el Eje 3)',
			'Demencia debida a enfermedad de Pick( en el eje 3)',
			'Trastornos del inicio y del mantenimiento del sue¤o [insomnios]',
			'Trastornos de somnolencia excesiva [hipersomnios]',
			'Apnea del sue¤o',
			'Narcolepsia y cataplexia',
			'Otros trastornos del sue¤o ( indicar enfermedad medica), tipo mixto',
			'Encopresis con estre¤imiento (en el eje 3)',
			'Impotencia de origen organico',
			'Otros trastornos especificados de los ¢rganos genitales masculinos',
			'Dispareunia',
			'Otras afecciones especificadas asociadas con los ¢rganos genitales femeninos y el ciclo me',
			'Incontinencia fecal',
			'Otra amnesia',
			'Otros s¡ntomas y signos que involucran la funci¢n cognoscitiva y la conciencia y los no es',
			'Otros s¡ntomas y signos que involucran la apariencia y el comportamiento',
			'Causas de morbilidad desconocidas y no especificadas',
			'Traumatismo intracraneal, no especificado',
			'Negligencia o abandono',
			'Abuso f¡sico',
			'Abuso sexual',
			'Efecto adverso no especificado de droga o medicamento',
			'Observaci¢n por sospecha de trastorno mental y del comportamiento',
			'Otros problemas relacionados con la educaci¢n y la alfabetizaci¢n',
			'Otros problemas y los no especificados relacionados con el empleo',
			'Problemas relacionados con el ajuste a las transiciones del ciclo vital',
			'Problemas relacionados con la adaptaci¢n cultural',
			'Problemas en la relaci¢n entre esposos o pareja',
			'Problemas en la relaci¢n con los padres y los familiares pol¡ticos',
			'Problemas relacionados con la desaparici¢n o muerte de un miembro de la familia',
			'Problemas relacionados con otros hechos estresantes que afectan a la familia y al hogar',
			'Otros problemas especificados relacionados con el grupo primario de apoyo',
			'Problema no especificado relacionado con el grupo primario de apoyo',
			'Otras consultas especificadas',
			'Otros problemas relacionados con el estilo de vida',
			'Historia personal de incumplimiento del régimen o tratamiento médico'
			);

	    $counts = count($codes);

	    for ($i=0; $i < $counts; $i++) { 
	    	factory(App\Diagnostic::class)->create([
		                'code' => $codes[$i],
	                    'description'      => $descriptions[$i]
	                ]);

	    }
    }

}
